### ISSUE TITLE
Error: invalid Module.php file for Datavis module

### ISSUE THREAD

**Issue by ZaraFinds** [omeka-s-modules/Datavis#1]
Hi,

I have installed this Datavis module on Omeka S version 3.0.2, but in the module section it says "Error: invalid Module.php file". In the directory the name of the module folder is "Datavis-main". Does changing the folder name fix the problem? If so what should I change it to?

Thank you

**Comment by jimsafley** [comment]
Renaming Datavis-main to Datavis should fix the problem. Note that this module is still under development and should not be used for production sites.

**Comment by ZaraFinds** [comment]
I changed the name and was able to install it. I look forward to the full development of this module. Thank you so much!
