### ISSUE TITLE
Testing: Item relationships dataset

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Datavis#15]
The [network-graph](https://github.com/omeka-s-modules/Datavis/tree/network-graph) branch introduces the "Item relationships" dataset and the "Network graph" and "Arc" diagrams. To test this your site is going to need a sizable pool of items that are interrelated via resource values. Add a new visualization and choose "Item relationships." Here you'll configure the dataset and the diagram. While testing, select both "Network graph" and "Arc" diagrams, and try out their configurations. Remember to generate the dataset after you configure it. View and interact with the diagrams.

**Comment by sharonmleon** [comment]
I am ridiculously excited about this.

**Comment by allanaaa** [comment]
@katknow can you also take a look at this one? I don't know about you but I probably only have 5-10 linked items in my test install right now.

**Comment by katknow** [comment]
This seems to be working as expected.

**Comment by allanaaa** [comment]
@jimsafley Are you happy with Katie's result on this, or would you like me to take a look? If you want, you can close this and open up a documentation issue.

**Comment by jimsafley** [comment]
I'll assume that this was tested on "a sizable pool of items that are interrelated via resource values" and close the issue.

**Comment by jimsafley** [comment]
Note that I've merged the `network-graph` branch into `main`, so you'll need to do further testing on that.

**Comment by jimsafley** [comment]
@sharonmleon I've added an option to limit relationships to selected properties.
