### ISSUE TITLE
Diagram page titles not showing in title attribute

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Datavis#18]
I'm not getting my diagram/page titles on their pages, only "site title - installation title". 

<img width="701" alt="Screenshot 2024-01-03 at 11 49 55" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/5f5ce15c-8fb0-45e3-a1ba-43f7d5c13f69">

I know they're meant to be dropped in as page blocks, but since we do offer a public URL for each a page title would be nice.

**Comment by jimsafley** [comment]
These diagrams are not in a page context, so there's no page title to display.

**Comment by allanaaa** [comment]
Since we offer people the direct URLs they will at some point want to use them as standalone pages. They would be good as browse pages, using the description field you provide to give some instructions. 

I would say, either don't give them public pages, or give them public pages properly, with titles.

**Comment by jimsafley** [comment]
I've added a "Data visualization" custom link to site navigation.

**Comment by allanaaa** [comment]
Can we also add the page title into the title attribute?

**Comment by jimsafley** [comment]
I pushed a change that adds the page title.
