### ISSUE TITLE
empty input option

### ISSUE THREAD

**Issue by sinanatra** [omeka-s-modules/Datavis#2]
Hello, i downloaded the module, and imported it into my local Omeka S instance. When i import it the input field remains empty: 

<img width="931" alt="Screenshot 2021-04-22 at 12 32 15" src="https://user-images.githubusercontent.com/20107875/115700296-d1654a00-a366-11eb-9aa8-88d5290ee6e7.png">

<img width="946" alt="Screenshot 2021-04-22 at 12 32 03" src="https://user-images.githubusercontent.com/20107875/115700288-d0341d00-a366-11eb-93d9-a1aa88a920e0.png">

What should i do to make it work?
Could you provide some documentation on how to use it?
Thanks in advance.

**Comment by jimsafley** [comment]
Thank you for your interest in this module, but it is still in development and not yet released. Once it is released, it will be available on the [Omeka S modules](https://omeka.org/s/modules/) page for download.
