### ISSUE TITLE
Testing: Site-level permissions

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Datavis#28]
Per #26, the "site-permissions" branch adds site-level permissions. Site managers (regardless of user role) are now able to create visualizations, and update and delete visualizations that they own. They are not permitted to update or delete visualizations that they do not own.

**Comment by allanaaa** [comment]
"Site manager" works well, but being "Site creator" allows me to proceed through the add-visualization process, then gives me an error when I try to save:

<img width="1336" alt="Screenshot 2024-02-13 at 16 44 42" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/8bc8c51d-f995-487b-be49-a1bc5c6d0145">

On a site where the user is not added at any level (Editor level install-wide), this appears to be true too - I can start to add a visualization, get all the way through to saving my settings.

**Comment by jimsafley** [comment]
Any site user who is not a "Manager" should not be able to see the edit links and add button. Are you directly linking to the add/edit pages?

**Comment by jimsafley** [comment]
I've removed the "Add a new visualization" link. Users without levels and site viewers / creators should be able to browse (but not add/edit) visualizations.

**Comment by allanaaa** [comment]
Works great now!
