### ISSUE TITLE
Testing: Color configuration

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Datavis#30]
The [color-config](https://github.com/omeka-s-modules/Datavis/compare/main...color-config) branch adds the ability for users to configure the color of their diagrams. Every diagram configuration section now includes a "Color fill" setting or a "Color scheme" setting. The "Color fill" setting accepts a hexadecimal color code. The "Color scheme" setting provides a handful of pre-set color schemes from which to choose.

**Comment by allanaaa** [comment]
Love it. Works great. 
If there was a way to improve it, I'd say when you select a colour scheme from the dropdown, we could show the 8-12 colours in a row of blocks below, just the way the help page does. But it's not necessary.
