### ISSUE TITLE
Documentation: Color configuration

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Datavis#31]
See #30

**Comment by jimsafley** [comment]
The NumericDataTypes module provides the "Histogram (time series)", "Line chart (time series)", and "Grouped line chart (time series)" diagram types. I plan to work on NumericDataType's data visualization implementation later in the year. Would you mind creating an issue in that module's repository to this effect?

**Comment by allanaaa** [comment]
Sure thing. This doc update is done, then!
