### ISSUE TITLE
Bulk-update datasets

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Datavis#32]
When a site has a lot of datasets, it could be useful to "Update all datasets" with a bulk action from the viz table.

<img width="928" alt="Screenshot 2024-06-18 at 12 15 23" src="https://github.com/omeka-s-modules/Datavis/assets/28012148/95eabac8-7787-49c8-a619-c9631d898998">

This has only occurred to me because Copy Resources creates drafts when it copies all the visualizations, and you need to re-generate all datasets and diagrams after you copy a site. But for users who want to keep everything up-to-date with their growing collections, bulk actions could also be useful. 

(Perhaps a future version of Copy Resources could also add a "Copy visualization" button if you, say, want to have identical visualizations set for each class of item, or something....)

**Comment by jimsafley** [comment]
I just pushed a change to this module that should make datasets copy over. Try it out.

**Comment by allanaaa** [comment]
Thanks, works great! 

Want to leave this open and consider bulk actions for a later release?

**Comment by jimsafley** [comment]
I'd rather not provide a bulk "update all datasets" feature. Given the memory needed to generate one dataset, it could bog down servers to generate all of them at once.
