### ISSUE TITLE
Testing: Data Visualization module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Datavis#4]
The Data Visualization module allows site administrators to generate datasets and render diagrams that reflect their data. To test the module, it's required to have a large, richly described collection of items assigned to a site. Note that a "visualization" consists of two parts: 1) a "dataset" that represents some portion of your data, and 2) a "diagram" that visually represents the dataset.

When administering a site, click on the "Data Visualization" link. You will land on the "Visualizations" browse page. Click on the "Add new visualization" button. You should land on the "Add visualization" page. Select a dataset type under "What would you like to visualize?" and click the "Next" button. You should land on the "Add visualization" page. This page is where you will configure your visualization, including the dataset and diagram.

Enter a title, description, and search query. Then configure your dataset and diagram. You will need some content expertise on your data to effectively configure a dataset. Should you need help finding the right metadata to use, the [DataCleaning](https://github.com/omeka-s-modules/DataCleaning) and [FacetedBrowse](https://github.com/omeka-s-modules/FacetedBrowse) modules (both unreleased) provide ways to analyse your resources in detail.

Once you've configured a dataset and diagram click the "Save and..." button, select the "Generate dataset" checkbox, then click "Stay on this visualization." You should land on the same page but with everything saved and a message that your dataset is being generated. After a few seconds (or more, depending on the amount of data) your dataset should be generated.

Now refresh the page. You should see a "View..." button. Click it and click on "Dataset." A new tab should open containing your dataset. Click on the "View..." button again ans click on "Diagram." A new tab should open containing your diagram in a public site context. Note that diagrams will only exist in a public site context. Check the dataset and diagram for any obvious inconsistencies or errors.

You may continue configuring the dataset and diagram. Just remember to generate the dataset after you've configured it. After making changes to the diagram, just refresh the public site page that you opened earlier. It should render the current state of the dataset and the current state of diagram configuration.

After you get the hang of this one visualization, add a new visualization of each type and make sure they all work as expected. By the end of testing your should have a handful of meaningful visualizations.

Now you'll need to add the visualizations to the public site. When editing a site page, click on the "Data visualization" block. You should see a new block on the page where you can select a visualization. Select one. Then click on another "Data visualization" block and select another. Do this on the same page until all of the visualizations you made are on the same page. Save the page and view the public site. You should see every visualization you made without errors or visual artifacts.

**Comment by katknow** [comment]
I'm still working on this one, but a quick observation is that you currently cannot fill in the field "item sets" for the option "count of items in item sets" in Safari, Chrome, or Firefox

**Comment by katknow** [comment]
I really like this module a lot! The visualizations generally look really nice, although sometimes the labels for the pie chart stack on top of each other and can't really be moved (this may just mean that your data isn't right for that kind of chart). It may be worth noting in any documentation that the labels might be cut off for bar/column charts until the margins are adjusted. All fields/drop downs/check boxes etc. worked other than the "item sets" field as described in my previous comment. One question--should the description be appearing on the public page? If not, axes might be useful (although I guess this could also be described in the title of the graph). Appears to work across browsers on laptop and mobile.

**Comment by jimsafley** [comment]
> One question--should the description be appearing on the public page?

Yes. I've added the description immediately under the title (7b9ef26f2c85eac76cc4ba33456d2baf2c452b87).

**Comment by jimsafley** [comment]
> you currently cannot fill in the field "item sets" for the option "count of items in item sets" in Safari, Chrome, or Firefox

This is likely because that form element only displays item sets that are assigned to the site. I could make it so users can select from _all_ item sets, but I'm not sure if this is preferable. @sharonmleon What do you think?

**Comment by katknow** [comment]
The description now appears below the title across browsers.

**Comment by katknow** [comment]
> 
> 
> > you currently cannot fill in the field "item sets" for the option "count of items in item sets" in Safari, Chrome, or Firefox
> 
> This is likely because that form element only displays item sets that are assigned to the site. I could make it so users can select from _all_ item sets, but I'm not sure if this is preferable. @sharonmleon What do you think?

@sleon and @jimsafley wanted to follow up re. the item sets field. I was trying to screenshot for documentation draft, and if it's not filled in you can't move forward.

**Comment by sharonmleon** [comment]
I'm sorry, I missed this question from @jimsafley. I do think it should be tied to the Item Sets that are attached to the site. So, @katknow the question is whether or not you have any item sets attached to your site in the Resources section. If you do, and it still doesn't work, then you've located a bug.

**Comment by jimsafley** [comment]
Yes, the Item sets field is required. If you're still not seeing item sets in that select menu, you'll need to assign at least one item set to the site. Go to **Site Resources > Item Sets** and assign an item set.

**Comment by katknow** [comment]
@jimsafley and @sharonmleon it was definitely operator error, it looks like I somehow managed to dump all my items into my test site and in the process remove them from their item sets. Thank you!

**Comment by sharonmleon** [comment]
Easy to do.
