### ISSUE TITLE
version constraint of "^3.1.0" + Omeka\Form\Element\Query" was not found 

### ISSUE THREAD

**Issue by sinanatra** [omeka-s-modules/Datavis#6]
Hello, i know that the module is in development and it has a version constraint of `"^3.1.0"`  (?).
However, since I wanted to test it, i temporarily changed the constraint, which leads me to the following error at `/add-dataset-type`: 

```
Laminas\Form\Exception\InvalidElementException
A plugin by the name "Omeka\Form\Element\Query" was not found in the plugin manager Laminas\Form\FormElementManager\FormElementManagerV3Polyfill

Details:

Laminas\Form\Exception\InvalidElementException: A plugin by the name "Omeka\Form\Element\Query" was not found in the plugin manager Laminas\Form\FormElementManager\FormElementManagerV3Polyfill in /Users/giacomonanni/Development/pina-o/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php:47
```

With that said, would it be possible to test the module or would it be available just for the next Omeka S release? (3.1.0)

**Comment by zerocrates** [comment]
Yeah, this module requires an upcoming release of Omeka S, which is why it has that constraint listed.
